# Generated by Django 4.1 on 2024-04-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flower", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flower",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="images"),
        ),
    ]
